apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-2-frontend
  namespace: furniaizer
  labels:
    app: ai-agent-2-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent-2-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-agent-2-frontend
    spec:
      initContainers:
      - name: discord-notification
        image: alpine/curl
        command:
        - sh
        - -c
        - |
          WEBHOOK_URL="${DISCORD_WEBHOOK_URL}"
          POD_NAME="${POD_NAME:-$(hostname)}"
          NAMESPACE="${POD_NAMESPACE:-default}"
          DEPLOYMENT="ai-agent-2-frontend"
          PRODUCTION_URL="${PRODUCTION_URL:-N/A}"
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"embeds\": [{
                \"title\": \"🚀 Pod Restarted\",
                \"description\": \"A pod has been restarted in the Kubernetes cluster.\",
                \"color\": 5814783,
                \"fields\": [
                  {\"name\": \"📛 Pod Name\", \"value\": \"$POD_NAME\", \"inline\": true},
                  {\"name\": \"📦 Deployment\", \"value\": \"$DEPLOYMENT\", \"inline\": true},
                  {\"name\": \"📍 Namespace\", \"value\": \"$NAMESPACE\", \"inline\": true},
                  {\"name\": \"🔗 URL\", \"value\": \"$PRODUCTION_URL\", \"inline\": false}
                ],
                \"timestamp\": \"$TIMESTAMP\"
              }]
            }" \
            "$WEBHOOK_URL"
        env:
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: ai-agent-2-frontend-secrets
              key: DISCORD_WEBHOOK_URL
        - name: PRODUCTION_URL
          valueFrom:
            secretKeyRef:
              name: ai-agent-2-frontend-secrets
              key: PRODUCTION_URL
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      containers:
      - name: frontend
        image: ghcr.io/teamshackathon/prod/ai-agent-2-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi