apiVersion: v1
kind: Service
metadata:
  name: ai-agent-2-frontend-service
  namespace: furniaizer
spec:
  selector:
    app: ai-agent-2-frontend
  ports:
  - port: 3001
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP